INPUT:
  MIN_SIZE_TRAIN: (2048,)
  MAX_SIZE_TRAIN: 2480
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TEST: 2480
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  TO_BGR255: False
  # This augmentation is intended for
  # dataset with small motion
  MOTION_LIMIT: 0.005
  MOTION_BLUR_PROB: 0.
  COMPRESSION_LIMIT: 0
  BRIGHTNESS: 0.
  CONTRAST: 0.
  SATURATION: 0.
  HUE: 0.
  AMODAL: False
VIDEO:
   TEMPORAL_WINDOW: 1000
   TEMPORAL_SAMPLING: 1000
   RANDOM_FRAMES_PER_CLIP: 2
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BOX_ON: True
  TRACK_ON: True

  BACKBONE:
    CONV_BODY: "DLA-34-FPN"

  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_SIZES: (6, 12, 24, 48, 96)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 300
    FPN_POST_NMS_TOP_N_TEST: 300
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
    MLP_HEAD_DIM: 1024

  # Track branch configuration
  TRACK_HEAD:
    MODEL: "EMM"
    PAD_PIXELS: 256
    POOLER_RESOLUTION: 7
    SEARCH_REGION: 5.0
    # For inference
    TRACK_THRESH: 0.6
    START_TRACK_THRESH: 0.95
    EMM:
      USE_CENTERNESS: False
      COSINE_WINDOW_WEIGHT: 0.1
      TRACK_LOSS_WEIGHT: 0.1

SOLVER:
  # Assume 8 GPUs
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (15000, 20000)
  MAX_ITER: 25000
  VIDEO_CLIPS_PER_BATCH: 16

DATASETS:
  # SET THIS PATH CORRECTLY
  ROOT_DIR: ""
  TRAIN: ("prime_air", )
  TEST: ("prime_air", )

DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 2

DTYPE: "float32"
